#!/usr/bin/sh
VERSION="#TAG# - #TAG_DATE#"

# shellcheck disable=SC1091
. /usr/share/terminate-notice/helpers

start_action "$(basename "$0")-$VERSION"

eval "$(load_config shutdown)"

# shellcheck disable=SC2154
_shutdown_delay="$(first_of "$SHUTDOWN_DELAY" "$shutdown_delay" "now")"
if [ -z "$_shutdown_delay" ]
then
    error 2 "$(basename "$0")-$VERSION" "No _shutdown_delay defined"
fi

# shellcheck disable=SC2154
_noshut="$(first_of "$NOSHUT" "$no_shut" "0")"
if [ -z "$_noshut" ]
then
    error 2 "$(basename "$0")-$VERSION" "No _noshut value defined"
fi

if [ "$VERIFY" = "1" ]
then
    echo "Action $(basename "$0")-$VERSION - INFO: Verified at start."
    exit 0
fi

# shellcheck disable=SC2154
if [ "$_noshut" = "1" ]
then
    /usr/sbin/shutdown -h "$_shutdown_delay"
else
    error 0 "$(basename "$0")-$VERSION" "Would shut down (halted by setting)"
fi